name:                battleship
version:             0.1.0.0
github:              "githubuser/battleship"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/battleship#readme>

dependencies:
- async
- base >= 4.7 && < 5
- network >= 2.7 && < 3.2
- network-bsd >= 2.7 && < 2.9
- brick >= 1.9
- vty >= 5.38
- text >= 2.0.2
- microlens >= 0.4.13.1
- microlens-th >= 0.4.3.14

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


source-dirs:
- ./src/
- ./src/client/
# - ./src/client/ClientUI/
- ./src/server/
executables:
  client:
    main: Main.hs
    source-dirs: app/client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  server:
    main: Main.hs
    source-dirs: app/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  battleship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
